
public enum ComitePossibles {
	C1 ("GENERAL ASSEMBLY I"),
	C2 ("GENERAL ASSEMBLY II"),
	C3 ("GENERAL ASSEMBLY III"),
	C4 ("GENERAL ASSEMBLY V"),
	C5 ("SECURITY COUNCIL"),
	C6 ("ECOSOC"),
	C7 ("COMMISSION ON THE STATUS OF WOMEN"),
	C8 ("COMMISSION ON NARTCOTIC DRUGS"),
	C9 ("COMMISSION FOR SOCIAL DEVELOPMENT"),
	C10 ("ECONOMIC AND SOCIAL COMMISSION FOR WESTERN ASIA"),
	C11 ("UNITED NATIONS ENVIRONMENT ASSEMBLY"),
	C12 ("UNESCO"),
	C13 ("INTERNATIONAL TELECOMMUNICATION UNION"),
	C14 ("FOOD AND AGRICULTURE ORGANIZATION OF THE UNITED NATIONS"),
	C15 ("UNITED NATIONS DEVELOPMENT PROGRAMME"),
	C16 ("UNITED NATIONS POPULATION FUND"),
	C17 ("A");
	
	private String name ="";
	
	ComitePossibles(String n){
		this.name=n;
	}
	
	public String toString(){
		return name;
	}
}
